// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPoolNet.Data;

#nullable disable

namespace TPoolNet.Migrations
{
    [DbContext(typeof(TPoolDbContext))]
    [Migration("20260830162151_InitialTPoolSchema")]
    partial class InitialTPoolSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tpool")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPoolNet.Entities.TablesConsumerType", b =>
                {
                    b.Property<int>("ConsumerTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumerTypeId"));

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("ConsumerTypeId");

                    b.ToTable("TablesConsumerType", "tpool");
                });

            modelBuilder.Entity("TPoolNet.Entities.TablesPool", b =>
                {
                    b.Property<long>("TablePoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TablePoolId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("sysname")
                        .HasDefaultValue("tpool");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("sysname");

                    b.Property<int>("TableTypeId")
                        .HasColumnType("int");

                    b.HasKey("TablePoolId");

                    b.HasIndex("TableTypeId");

                    b.HasIndex("SchemaName", "TableName")
                        .IsUnique();

                    b.ToTable("TablesPool", "tpool");
                });

            modelBuilder.Entity("TPoolNet.Entities.TablesType", b =>
                {
                    b.Property<int>("TableTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableTypeId"));

                    b.Property<string>("DdlTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPoolSize")
                        .HasColumnType("int");

                    b.Property<string>("TablePrefix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TableTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("TablesType", "tpool");
                });

            modelBuilder.Entity("TPoolNet.Entities.TablesUsage", b =>
                {
                    b.Property<long>("TablePoolId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BookedAtUtc")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("ConsumerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DeadlineUtc")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<DateTime>("HeartbeatUtc")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("TablePoolId");

                    b.ToTable("TablesUsage", "tpool");
                });

            modelBuilder.Entity("TPoolNet.Entities.TablesUsageHistory", b =>
                {
                    b.Property<long>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistoryId"));

                    b.Property<DateTime>("BookedAtUtc")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("ConsumerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReleaseReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Explicit");

                    b.Property<DateTime>("ReleasedAtUtc")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<long>("TablePoolId")
                        .HasColumnType("bigint");

                    b.HasKey("HistoryId");

                    b.HasIndex("BookedAtUtc");

                    b.HasIndex("TablePoolId");

                    b.ToTable("TablesUsageHistory", "tpool");
                });

            modelBuilder.Entity("TPoolNet.Entities.TablesPool", b =>
                {
                    b.HasOne("TPoolNet.Entities.TablesType", "TableType")
                        .WithMany("Tables")
                        .HasForeignKey("TableTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TableType");
                });

            modelBuilder.Entity("TPoolNet.Entities.TablesUsage", b =>
                {
                    b.HasOne("TPoolNet.Entities.TablesPool", "TablePool")
                        .WithOne("ActiveUsage")
                        .HasForeignKey("TPoolNet.Entities.TablesUsage", "TablePoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TablePool");
                });

            modelBuilder.Entity("TPoolNet.Entities.TablesPool", b =>
                {
                    b.Navigation("ActiveUsage");
                });

            modelBuilder.Entity("TPoolNet.Entities.TablesType", b =>
                {
                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
